# Generated by Django 5.0.1 on 2024-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0002_carbrand_parking_car_parkingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='file',
            field=models.FileField(default=None, upload_to='', verbose_name='car_file/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='/car_image/'),
            preserve_default=False,
        ),
    ]
