# Generated by Django 5.0.1 on 2024-03-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0003_car_file_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='car_file/'),
        ),
    ]
